# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
#

require 'simpler_workflow'
require 'aws/simple_workflow'
require 'pry'
require 'logging'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  config.before :each do
    AWS.stub!
    AWS.config(:access_key_id => 'TESTKEY', :secret_access_key => 'TESTSECRET')
  end

	$logger = Logging.logger(STDOUT)
end

class SimplerWorkflow::Workflow::WorkflowEventHandler
  def workflow_event_handler?
    is_a?(SimplerWorkflow::Workflow::WorkflowEventHandler)
  end
end
